[template]
# Files listed here will not be processed by the template engine when a project is generated.
# This is needed when files contains curly brackets as in `v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}`.
# The files will be copied 1:1 to the target project. To avoid shipping them completely add them to `.genignore`.
exclude = [".circleci/config.yml"]

[placeholders.version]
type = "string"
choices = ["full", "minimal"]
prompt = """This template has 2 versions:

- The full template includes example logic in case you're new to CosmWasm smart contracts.
- The minimal template assumes you already know how to write your own logic, includes the bare minimum and doesn't get in your way.

Which version do you want to generate?"""
default = "full"

[conditional.'version == "minimal"']
ignore = [
  "Developing.md",
  "Importing.md",
  "Publishing.md",
  "src/integration_tests.rs",
]
