on: [push, pull_request]

name: Check Templates

jobs:
  test-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install cargo-generate
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-generate --features vendored-openssl

      - name: Test all templates
        run: ${{ github.workspace }}/.github/scripts/test_generate.sh


